### ISSUE TITLE
Design extensions to manifest to support multiple tests per sample

### ISSUE THREAD

**Issue by nditada** [instedd/cdp#144]
Scenarios to support:
* Event containing only a sample with PII but no test
* Events with tests referring to a sample (both reported as an independent sample before or implicitly created by a previous tests with the same sample ID)
* Events with multiple tests for the same sample

**Comment by nditada** [comment]
Note from IP: This implies normalizing the PII encrypted field from the events table to a sample table (also encrypted).

**Comment by nditada** [comment]
Since supporting events that contain samples with PII but no tests implies redifinig and spliting the concept of "event" (event1:thing reported from the device which may or may not containg test data, event2: row in the table 'events' and indexed containing test data to which apps can subscribe), we will hold on doing this change until there's evidence of the use case, i.e. there are devices that report samples separated from test results.

**Comment by spalladino** [comment]
Support the following cases for merging event and sample information, ie case 2:

 * On new event, create event and sample
* On new event with no sample uid, create event and sample with no uid
* On new event with existing sample uid, update existing sample and existing institution events for that sample uid
* On new event with existing sample uid and no sample data, use existing sample data
* On new event with existing event id and device id, update existing event merging data from the new one, update existing sample merging data from the new one, and institution events for that sample uid
* On new event with existing event id and different sample uid, create event and link to new sample with new uid

**Comment by spalladino** [comment]
For case 3 (Events with multiple tests for the same sample) we are supporting multiple events in the same payload, though each must specify its own sample information.
