### ISSUE TITLE
Design interface of shapefiles for NNDD

### ISSUE THREAD

**Issue by nditada** [instedd/cdp#154]
NNDD needs a way to query shapefiles to highlight areas in a scalable way. Right now it's obtaining 1 topojson for each admin level which will not scale.
Analyze alternatives and design something:
- Do we want to expose this from CDx? As public directory? as endpoint with computed and cached results?
- Do we want to extract this to a separate reusable service/component? Can we reuse/contribute to Mapzen?

**Comment by nekron** [comment]
The location service was created.
