### ISSUE TITLE
CSV is not inserted into the date base

### ISSUE THREAD

**Issue by mmuller** [instedd/cdp#167]
Found in version: 
Web app: 20150312.194623-84cf2d1
Windows client: 7fbfd63

Preconditions:
There is a Windows client installed
There is a Device 'Foo' in the Web App
The Windows client has the token of the Device 'Foo'

Steps:
Add a CSV in the outbox folder. The CSV includes 5 events.
Go to the playground of the Web App
Search the Events where the Device uuid is the uuid of the Device 'Foo' 

Obtained:
No events found

Expected:
The events for the Device 'Foo' should be found

Additional information:
Device uuid used in this test: b2eb1609-769c-2c51-7218-e07b559af980

**Comment by pmallol** [comment]
The CSV should be encoded using UTF-8 to work.

**Comment by mmuller** [comment]
Related to #206
