### ISSUE TITLE
The Events are not filtered by Laboratory when they are exposed to another App

### ISSUE THREAD

**Issue by mmuller** [instedd/cdp#181]
Found in version: 20150318.133335-5c1714f

Preconditions:
There is a Laboratory 'Foo'
There is a filter where the Laboratory name is 'Foo'
There is a Hub task where the new CDX test for the Laboratory 'Foo' are received as event

Steps:
Create a new Test in order to submit a new event

Obtained:
The events for all the Laboratories are exposed (exposed to Hub in this test). They are not filtered by Lab.

Expected:
Only the events for the Laboratory 'Foo' should be exposed

**Comment by nekron** [comment]
It's working on version hotfix-0.3.4-27-g269e83a
