### ISSUE TITLE
After deleting a Hub task the CDX Subscriber cannot be removed

### ISSUE THREAD

**Issue by mmuller** [instedd/cdp#183]
Found in version: 20150318.190402-c0469e9
Hub version: 1a700c0

Preconditions:
There is a Hub Task where the event is a new test result from CDX. (Subscriber 'Foo' for CDX)

Steps:
Remove the Hub Task
Go to the Subscriber listing
Open the Subscriber 'Foo'
Try to remove the Subscriber

Obtained:
404 Page not found is displayed

Expected:
Since the Subscriber is not being used it can be removed

**Comment by nekron** [comment]
The subscribers are being removed by the hub. There is no need to delete a subscriber.
