### ISSUE TITLE
Support filtering by event_id in query API

### ISSUE THREAD

**Issue by spalladino** [instedd/cdp#205]
Filtering by event_id is ignored

**Comment by spalladino** [comment]
There is an explicit `params.delete(:event)` in the API endpoint, that is causing this filter to be ignored. We will rename parameter to `event_id` in filters to support this filter. @nekron please confirm if this is ok, as it is a change on the default fields mapping in `cdx_api_elasticsearch`.

**Comment by spalladino** [comment]
Should be fixed on merging PR https://github.com/instedd/cdx-api-elasticsearch/pull/5

**Comment by mmuller** [comment]
Ok in version: hotfix-0.3.4-27-g269e83a
