### ISSUE TITLE
Invalid format for uploaded CSV file

### ISSUE THREAD

**Issue by spalladino** [instedd/cdp#206]
Files exported from EpiCenter in non-UTF8 format yield the error `invalid byte sequence in UTF-8`

**Comment by nekron** [comment]
Spanish version of Windows XP exports automatically in UTF-16. Use https://github.com/brianmario/charlock_holmes or another to automatically detect the encoding.

**Comment by spalladino** [comment]
Alternative gem for auto detection, in pure Ruby https://github.com/jmhodges/rchardet

**Comment by mmuller** [comment]
Ok in version: hotfix-0.3.4-27-g269e83a
