### ISSUE TITLE
Orphan Device Model should be highlighted in the Device edition

### ISSUE THREAD

**Issue by mmuller** [instedd/cdp#217]
Found in version: hotfix-0.3.7-32-g33be34e

Preconditions: 
There is a Manifest 'A' that include a Device Model 'Foo'
There is a Device 'Bar' linked to the Device Model 'Foo'

Steps:
Delete the Manifest 'A'
Go to edit the Device 'Bar'

Obtained: The Device 'Bar' is linked to the Device Model 'Foo', but this Device Model is not shown in the Device 'Bar' edition.

Expected: Orphan Device Model should be displayed and highlighted in the Device edition. A hint could be included to notify that the Manifest was removed. 
The Device that include an orphan Device Model should be highlighted in the Device listing. 

![screen shot 2015-04-24 at 10 29 15 am](https://cloud.githubusercontent.com/assets/518152/7319549/ce2d17aa-ea6c-11e4-9e4d-97166dfbfc9f.png)

![screen shot 2015-04-24 at 10 29 51 am](https://cloud.githubusercontent.com/assets/518152/7319559/dc3e539a-ea6c-11e4-954c-9ddbc9f32629.png)

**Comment by nditada** [comment]
I would say that Manifests cannot be deleted when there are devices that are using them. @nekron what do you think?

**Comment by nekron** [comment]
Agree. See #267.

**Comment by nekron** [comment]
Agree.
