### ISSUE TITLE
If the CDX client is uninstalled while the UI is running an error is thrown

### ISSUE THREAD

**Issue by mmuller** [instedd/cdp#313]
Preconditions:
There is a CDX client already installed
The client UI is running

Steps:
Don't close de client UI
Uninstall the app

Obtained:
If the CDX client is uninstalled while the UI is running an error is thrown

Error detail:
'Stderr was Permission denied (publickey,keyboard-interactive).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]'

Expected:
When uninstalling the app the process should be stopped

**Comment by nekron** [comment]
Moved to https://github.com/instedd/cdx-sync-client/issues/28
