### ISSUE TITLE
Endpoint providing Locations

### ISSUE THREAD

**Issue by waj** [instedd/cdp#69]
starting at location and specifying sub-levels,
TBD: integrate with OSM, provide lat-long, boundaries, extract as platform service? re-work w Resmap?

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/cdp/issue/69
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-07-24 15:39:15+00:00

**Comment by nditada** [comment]
Solved with location service, #227
