### ISSUE TITLE
Empty queries should not be executed

### ISSUE THREAD

**Issue by waj** [instedd/cdp#84]
* Go to the Playground
* Don't complete the text area 'Query string'
* Press 'Query'
* 
* Expected: The query should not be executed
* 
* Actual: All events are thrown

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/cdp/issue/84
- Originally Reported By: Mauricio Müller
- Originally Created At: 2014-08-05 15:01:35+00:00

**Comment by pmallol** [comment]
After clicking the 'Query' button, all events are shown in the Response div.
