### ISSUE TITLE
Link to create a 'saved filter' is not being displayed

### ISSUE THREAD

**Issue by waj** [instedd/cdp#98]
-Go to 'events' page
-Fill the 'condition' filed with 'MTB,positive'
-Press 'Filter'

Expected: The link to create a 'saved filter' is displayed
Obtained: Link to create a 'saved filter' is not being displayed

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/cdp/issue/98
- Originally Reported By: Mauricio Müller
- Originally Created At: 2014-08-14 17:55:35+00:00

**Comment by nditada** [comment]
By design the subscriber link was not shown unless a lab was selected, remove that restriction.

**Comment by flbulgarelli** [comment]
Hi, @nditada, are you saying that the such link should appear if you filter by condition and laboratory? It seems it is not occurring either.

**Comment by flbulgarelli** [comment]
Currently you can not create subscribers directly anymore - you need to have a saved filter. So the issue now is that the link to create saved filter is not being rendered

**Comment by pmallol** [comment]
Ok in version 20150320.200801-ebc0288
